import {
    SiFastapi,
    SiSpringboot,
    SiDotnet,
    SiLaravel,
    SiNodedotjs,
    SiReact,
    SiAngular,
    SiVuedotjs,
    SiTypescript,
    SiJavascript,
    SiHtml5,
    SiCss3,
    SiTailwindcss,
    SiBootstrap,
    SiExpo,
    SiDocker,
    SiGithubactions,
    SiSonarcloud,
    SiPostgresql,
    SiMysql,
    SiRedis,
    SiFirebase,
    SiGit,
    SiSqlalchemy,
} from 'react-icons/si';
import { FaDatabase, FaCogs, FaFileContract, FaFilePdf } from 'react-icons/fa';
import { DiMsqlServer } from 'react-icons/di';


export const TECH_ICONS = {
    FastAPI: SiFastapi,
    'Spring Boot': SiSpringboot,
    '.NET': SiDotnet,
    Laravel: SiLaravel,
    'Node.js': SiNodedotjs,
    React: SiReact,
    Angular: SiAngular,
    'Vue.js': SiVuedotjs,
    TypeScript: SiTypescript,
    JavaScript: SiJavascript,
    HTML5: SiHtml5,
    CSS3: SiCss3,
    TailwindCSS: SiTailwindcss,
    Bootstrap: SiBootstrap,
    'React Native': SiReact,
    Expo: SiExpo,
    Docker: SiDocker,
    'GitHub Actions': SiGithubactions,
    SonarCloud: SiSonarcloud,
    PostgreSQL: SiPostgresql,
    MySQL: SiMysql,
    'SQL Server': DiMsqlServer,
    Redis: SiRedis,
    Firebase: SiFirebase,
    Alembic: SiSqlalchemy,
    Git: SiGit,
    XML: FaDatabase,
    'Firma Digital': FaFileContract,
    PDF: FaFilePdf,
    Maven: FaCogs,
    OpenAI: FaCogs,
    Vite: SiReact,
    DDD: FaCogs,
};
